#############################################################################
# Makefile for building: ./qmloscilloscope.js
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  ../qmloscilloscope.pro
# Template: app
# Command: /home/pop_os/Qt/5.14.2/wasm_32/bin/qmake -o Makefile ../qmloscilloscope.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -O3 -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
INCPATH       = -I../../qmloscilloscope -I. -I/home/pop_os/Qt/5.14.2/wasm_32/include -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtQmlModels -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtNetwork -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore -I. -I/home/pop_os/.emscripten_ports/openssl/include -I/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/wasm-emscripten
QMAKE         = /home/pop_os/Qt/5.14.2/wasm_32/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/pop_os/Qt/5.14.2/wasm_32/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/pop_os/Qt/5.14.2/wasm_32/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qmloscilloscope.js1.0.0
DISTDIR = /media/storage/carlo/Documents/temp1/qmloscilloscope/build/.tmp/qmloscilloscope.js1.0.0
LINK          = em++
LFLAGS        = -s "BINARYEN_TRAP_MODE='clamp'" -s WASM=1 -s FULL_ES2=1 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=["UTF16ToString","stringToUTF16"] --bind -O3 -s ALLOW_MEMORY_GROWTH=1
LIBS          = $(SUBLIBS) /home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/libqwasm.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5EventDispatcherSupport.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5FontDatabaseSupport.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libqtfreetype.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5EglSupport.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqgif.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqicns.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqico.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqjpeg.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqtga.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqtiff.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqwbmp.a /home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqwebp.a /home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Layouts/libqquicklayoutsplugin.a /home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick.2/libqtquick2plugin.a /home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Controls/libqtquickcontrolsplugin.a /home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Window.2/libwindowplugin.a /home/pop_os/Qt/5.14.2/wasm_32/qml/QtQml/libqmlplugin.a /home/pop_os/Qt/5.14.2/wasm_32/qml/QtCharts/libqtchartsqml2.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Charts.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Quick.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Widgets.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Gui.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libqtlibpng.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libqtharfbuzz.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5QmlModels.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Qml.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Network.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Core.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libqtpcre2.a   
AR            = emar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../main.cpp \
		../datasource.cpp /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_plugin_import.cpp \
		/media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_qml_plugin_import.cpp \
		qrc_resources.cpp \
		moc_datasource.cpp
OBJECTS       = main.o \
		datasource.o \
		qmloscilloscope.js_plugin_import.o \
		qmloscilloscope.js_qml_plugin_import.o \
		qrc_resources.o \
		moc_datasource.o
DIST          = ../qml/qmloscilloscope/* \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/spec_pre.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/sanitize.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/gcc-base.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/clang.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/qdevice.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/device_config.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/emcc_ver.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/qconfig.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_charts.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_charts_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_core.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_network.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_networkauth.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_purchasing.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwebgl.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt_functions.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt_config.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/spec_post.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/exclusive_builds.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/toolchain.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/default_pre.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/default_pre.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resolve_config.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/default_post.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/wasm.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/warn_on.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resources_functions.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resources.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/moc.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/unix/opengl.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/uic.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qmake_use.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/file_copies.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/testcase_targets.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/exceptions.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/yacc.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/lex.prf \
		../../qmloscilloscope.pro ../datasource.h ../main.cpp \
		../datasource.cpp
QMAKE_TARGET  = qmloscilloscope.js
DESTDIR       = ./
TARGET        = ./qmloscilloscope.js


first: all
####### Build rules

./qmloscilloscope.js: /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Charts.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Widgets.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Quick.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Gui.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5QmlModels.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Qml.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Network.a /home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Core.a $(OBJECTS)  apphtml appjs appsvg
	@test -d ./ || mkdir -p ./
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../qmloscilloscope.pro /home/pop_os/Qt/5.14.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf /home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/spec_pre.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/sanitize.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/gcc-base.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/clang.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/qdevice.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/device_config.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/emcc_ver.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/qconfig.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_charts.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_charts_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_core.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_network.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_networkauth.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_purchasing.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwebgl.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt_functions.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt_config.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/spec_post.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/exclusive_builds.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/toolchain.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/default_pre.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/default_pre.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resolve_config.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/default_post.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/wasm.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/warn_on.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resources_functions.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resources.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/moc.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/unix/opengl.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/uic.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qmake_use.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/file_copies.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/testcase_targets.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/exceptions.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/yacc.prf \
		/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/lex.prf \
		../qmloscilloscope.pro \
		../resources.qrc \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/libqwasm.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqgif.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqicns.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqico.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqjpeg.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqtga.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqtiff.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqwbmp.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqwebp.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Charts.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Widgets.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Quick.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Gui.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5QmlModels.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Qml.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Network.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Core.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick.2/libqtquick2plugin.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Window.2/libwindowplugin.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQml/libqmlplugin.prl \
		/home/pop_os/Qt/5.14.2/wasm_32/qml/QtCharts/libqtchartsqml2.prl
	$(QMAKE) -o Makefile ../qmloscilloscope.pro
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/spec_pre.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/sanitize.conf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/gcc-base.conf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/common/clang.conf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/qdevice.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/device_config.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/emcc_ver.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/qconfig.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_bodymovin_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_charts.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_charts_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_core.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_core_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_datavisualization.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gamepad.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gui.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_gui_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimedia.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_network.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_network_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_networkauth.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_opengl.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_printsupport.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_purchasing.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qml.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qml_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmltest.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quick.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quick_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_repparser.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_scxml.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_sensors.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_svg.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_svg_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_testlib.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uitools.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webchannel.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_websockets.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webview.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_webview_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_widgets.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xml.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xml_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qgif.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qicns.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qico.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtga.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwebgl.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt_functions.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt_config.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/spec_post.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/exclusive_builds.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/toolchain.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/default_pre.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/default_pre.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resolve_config.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/default_post.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/wasm/wasm.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/warn_on.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qt.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resources_functions.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/resources.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/moc.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/unix/opengl.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/uic.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/qmake_use.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/file_copies.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/testcase_targets.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/exceptions.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/yacc.prf:
/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/lex.prf:
../qmloscilloscope.pro:
../resources.qrc:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/libqwasm.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqgif.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqicns.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqico.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqjpeg.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqtga.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqtiff.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqwbmp.prl:
/home/pop_os/Qt/5.14.2/wasm_32/plugins/imageformats/libqwebp.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Charts.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Widgets.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Quick.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Gui.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5QmlModels.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Qml.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Network.prl:
/home/pop_os/Qt/5.14.2/wasm_32/lib/libQt5Core.prl:
/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick.2/libqtquick2plugin.prl:
/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl:
/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl:
/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQuick/Window.2/libwindowplugin.prl:
/home/pop_os/Qt/5.14.2/wasm_32/qml/QtQml/libqmlplugin.prl:
/home/pop_os/Qt/5.14.2/wasm_32/qml/QtCharts/libqtchartsqml2.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../qmloscilloscope.pro

qmake_all: FORCE


all: Makefile ./qmloscilloscope.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../datasource.h $(DISTDIR)/
	$(COPY_FILE) --parents ../main.cpp ../datasource.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_plugin_import.cpp /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_qml_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: /home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/wasm_shell.html
	sed -e s/@APPNAME@/qmloscilloscope/g /home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/wasm_shell.html > /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.html

appjs: /home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/qtloader.js
	cp -f /home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/qtloader.js /media/storage/carlo/Documents/temp1/qmloscilloscope/build

appsvg: /home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/qtlogo.svg
	cp -f /home/pop_os/Qt/5.14.2/wasm_32/plugins/platforms/qtlogo.svg /media/storage/carlo/Documents/temp1/qmloscilloscope/build

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) qmloscilloscope.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: ../resources.qrc \
		/home/pop_os/Qt/5.14.2/wasm_32/bin/rcc \
		../qml/qmloscilloscope/ControlPanel.qml \
		../qml/qmloscilloscope/MultiButton.qml \
		../qml/qmloscilloscope/main.qml \
		../qml/qmloscilloscope/ScopeView.qml
	/home/pop_os/Qt/5.14.2/wasm_32/bin/rcc -name resources ../resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/data/dummy.cpp
	em++ -pipe -O3 -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra -dM -E -o moc_predefs.h /home/pop_os/Qt/5.14.2/wasm_32/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_datasource.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_datasource.cpp
moc_datasource.cpp: ../datasource.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QObject \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobject.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobjectdefs.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qnamespace.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qconfig-bootstrapped.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qconfig.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtcore-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsystemdetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qprocessordetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcompilerdetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtypeinfo.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsysinfo.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlogging.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qflags.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbasicatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_bootstrap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qgenericatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_cxx11.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_msvc.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qglobalstatic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmutex.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qnumeric.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qversiontagging.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobjectdefs_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstring.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qchar.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbytearray.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qrefcount.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qarraydata.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringliteral.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringalgorithms.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringview.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringbuilder.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qalgorithms.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qiterator.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qhashfunctions.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpair.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvector.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontainertools_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpoint.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbytearraylist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringlist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qregexp.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringmatcher.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcoreevent.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qscopedpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmetatype.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvarlengtharray.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontainerfwd.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobject_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QAbstractSeries \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qabstractseries.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QChartGlobal \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qchartglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QtGlobal \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QAbstractAxis \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qabstractaxis.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QPen \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpen.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtguiglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtgui-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qcolor.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qrgb.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qrgba64.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qbrush.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qmatrix.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpolygon.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qrect.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmargins.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsize.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qregion.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindowdefs.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindowdefs_win.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qdatastream.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qiodevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qline.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtransform.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpainterpath.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qimage.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpaintdevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpixelformat.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpixmap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsharedpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qshareddata.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qhash.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsharedpointer_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QFont \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qfont.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QVariant \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvariant.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qdebug.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtextstream.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlocale.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qset.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontiguouscache.h \
		moc_predefs.h \
		/home/pop_os/Qt/5.14.2/wasm_32/bin/moc
	/home/pop_os/Qt/5.14.2/wasm_32/bin/moc $(DEFINES) --include /media/storage/carlo/Documents/temp1/qmloscilloscope/build/moc_predefs.h -I/home/pop_os/Qt/5.14.2/wasm_32/mkspecs/wasm-emscripten -I/media/storage/carlo/Documents/temp1/qmloscilloscope -I/home/pop_os/Qt/5.14.2/wasm_32/include -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtQmlModels -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtNetwork -I/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore -I. ../datasource.h -o moc_datasource.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: ../main.cpp /home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets/QApplication \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets/qapplication.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets/qtwidgetsglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtguiglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qconfig-bootstrapped.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qconfig.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtcore-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsystemdetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qprocessordetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcompilerdetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtypeinfo.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsysinfo.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlogging.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qflags.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbasicatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_bootstrap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qgenericatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_cxx11.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_msvc.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qglobalstatic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmutex.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qnumeric.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qversiontagging.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtgui-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets/qtwidgets-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcoreapplication.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstring.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qchar.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbytearray.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qrefcount.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qnamespace.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qarraydata.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringliteral.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringalgorithms.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringview.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringbuilder.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobject.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobjectdefs.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobjectdefs_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qalgorithms.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qiterator.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qhashfunctions.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpair.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvector.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontainertools_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpoint.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbytearraylist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringlist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qregexp.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringmatcher.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcoreevent.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qscopedpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmetatype.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvarlengtharray.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontainerfwd.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobject_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qeventloop.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindowdefs.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindowdefs_win.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsize.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmargins.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qcursor.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets/qdesktopwidget.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets/qwidget.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpaintdevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qrect.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpalette.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qcolor.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qrgb.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qrgba64.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qbrush.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qmatrix.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpolygon.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qregion.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qdatastream.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qiodevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qline.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtransform.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpainterpath.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qimage.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpixelformat.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpixmap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsharedpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qshareddata.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qhash.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsharedpointer_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qfont.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qfontmetrics.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qfontinfo.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtWidgets/qsizepolicy.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qkeysequence.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qevent.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvariant.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qdebug.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtextstream.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlocale.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qset.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontiguouscache.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qurl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qurlquery.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qfile.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qfiledevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qvector2d.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtouchdevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qguiapplication.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qinputmethod.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/QQmlContext \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlcontext.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qjsvalue.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qtqmlglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qtqml-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtNetwork/qtnetworkglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtNetwork/qtnetwork-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/QQuickView \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qquickview.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qquickwindow.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qtquickglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qtquick-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qsgrendererinterface.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qsgnode.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qsggeometry.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qopengl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qt_windows.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qopengles2ext.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qopenglext.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QRectF \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QMatrix4x4 \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qmatrix4x4.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qvector3d.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qvector4d.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qquaternion.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qgenericmatrix.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindow.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QObject \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QEvent \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QMargins \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QRect \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qsurface.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qsurfaceformat.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qicon.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqml.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlprivate.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlparserstatus.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlpropertyvaluesource.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmllist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmetaobject.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmldebug.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/QQmlEngine \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlengine.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qjsengine.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlerror.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QDir \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qdir.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qfileinfo.h \
		../datasource.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QAbstractSeries \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qabstractseries.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QChartGlobal \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qchartglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QtGlobal \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QAbstractAxis \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qabstractaxis.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QPen \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpen.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QFont \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QVariant
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../main.cpp

datasource.o: ../datasource.cpp ../datasource.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QObject \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobject.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobjectdefs.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qnamespace.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qconfig-bootstrapped.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qconfig.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtcore-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsystemdetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qprocessordetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcompilerdetection.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtypeinfo.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsysinfo.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlogging.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qflags.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbasicatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_bootstrap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qgenericatomic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_cxx11.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qatomic_msvc.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qglobalstatic.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmutex.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qnumeric.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qversiontagging.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobjectdefs_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstring.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qchar.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbytearray.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qrefcount.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qarraydata.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringliteral.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringalgorithms.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringview.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringbuilder.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qalgorithms.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qiterator.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qhashfunctions.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpair.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvector.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontainertools_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpoint.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qbytearraylist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringlist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qregexp.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qstringmatcher.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcoreevent.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qscopedpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmetatype.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvarlengtharray.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontainerfwd.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qobject_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QAbstractSeries \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qabstractseries.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QChartGlobal \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qchartglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QtGlobal \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QAbstractAxis \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qabstractaxis.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QPen \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpen.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtguiglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtgui-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qcolor.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qrgb.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qrgba64.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qbrush.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qmatrix.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpolygon.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qrect.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmargins.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsize.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qregion.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindowdefs.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindowdefs_win.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qdatastream.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qiodevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qline.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtransform.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpainterpath.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qimage.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpaintdevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpixelformat.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qpixmap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsharedpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qshareddata.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qhash.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qsharedpointer_impl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QFont \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qfont.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QVariant \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qvariant.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmap.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qdebug.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qtextstream.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qlocale.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qset.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcontiguouscache.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QXYSeries \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qxyseries.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QBrush \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/QAreaSeries \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCharts/qareaseries.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/QQuickView \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qquickview.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qquickwindow.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qtquickglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qtqmlglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qtqml-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtNetwork/qtnetworkglobal.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtNetwork/qtnetwork-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qtquick-config.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qsgrendererinterface.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qsgnode.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qsggeometry.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qopengl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qt_windows.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qopengles2ext.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qopenglext.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QRectF \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/QMatrix4x4 \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qmatrix4x4.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qvector3d.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qvector4d.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qquaternion.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qgenericmatrix.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qwindow.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QEvent \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QMargins \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QRect \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qsurface.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qsurfaceformat.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qicon.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qcursor.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qevent.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qkeysequence.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qurl.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qurlquery.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qfile.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qfiledevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qvector2d.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qtouchdevice.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqml.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlprivate.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qpointer.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlparserstatus.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlpropertyvaluesource.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmllist.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmetaobject.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmldebug.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/QQuickItem \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQuick/qquickitem.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlcomponent.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qqmlerror.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtQml/qjsvalue.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QList \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtGui/qaccessible.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qcoreapplication.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qeventloop.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QDebug \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QRandomGenerator \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qrandom.h \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/QtMath \
		/home/pop_os/Qt/5.14.2/wasm_32/include/QtCore/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datasource.o ../datasource.cpp

qmloscilloscope.js_plugin_import.o: /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmloscilloscope.js_plugin_import.o /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_plugin_import.cpp

qmloscilloscope.js_qml_plugin_import.o: /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_qml_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmloscilloscope.js_qml_plugin_import.o /media/storage/carlo/Documents/temp1/qmloscilloscope/build/qmloscilloscope.js_qml_plugin_import.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_datasource.o: moc_datasource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datasource.o moc_datasource.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope || mkdir -p $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope/ 


install_js_file: first FORCE
	@test -d $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope || mkdir -p $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope
	$(QINSTALL_PROGRAM) /media/storage/carlo/Documents/temp1/qmloscilloscope/qmloscilloscope.js $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope/qmloscilloscope.js

uninstall_js_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope/qmloscilloscope.js
	-$(DEL_DIR) $(INSTALL_ROOT)/home/pop_os/Qt/Examples/Qt-5.14.2/charts/qmloscilloscope/ 


install: install_target install_js_file  FORCE

uninstall: uninstall_target uninstall_js_file  FORCE

FORCE:

